<?php
/**
 * 后台登录类
 * User: 小宝
 * Date: 2017年9月11日
 * Time: 14:28
 */
namespace app\admin\controller;

use think\Config;
use think\Controller;
use \think\View;

class Login extends Controller{

    //初始化
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录页面
     */
    public function index(){
        $view = new View();
        return $view->fetch('login');
    }

    /**
     * 处理后台登录接口
     *
     * 1、验证传递数据格式是否正确
     *  1.1 数据格式错误  返回提示
     *
     * 2、通过用户名获取管理员数据
     *  2.1 管理员不存在  返回提示
     *
     * 3、验证密码是否正确
     *  3.1 密码错误返回提示
     *
     * 4、记录登录日志 授权key
     *  4.1 登录成功 返回用户数据
     */
    public function login(){
        if($this->request->isPost()) {
            $data = $this->request->only(['username', 'password', 'verify']);
            $result = $this->validate($data, 'Login.login');
            if ($result !== true)
                return json(['data' => [], 'code' => 201, 'msg' => $result]);

            $res_admin = db('admin')->field('id,password,status')->where(['username' => $data['username']])->find();
            //用户名不存在
            if (!is_array($res_admin))
                return json(['data' => [], 'code' => 202, 'msg' => '用户名或密码错误#1']);
            //密码错误
            if ($res_admin['password'] !== md5($data['password'] . Config::get('salt')))
                return json(['data' => [], 'code' => 203, 'msg' => '用户名或密码错误#2']);

            //当前管理员被禁用
            if ($res_admin['status'] !== 1)
                return json(['data' => [], 'code' => 204, 'msg' => '很抱歉，您已被禁用！']);

            //记录登录日志，返回登录key
            $key = $res_admin['id'].time();
            $res_login = db('admin_login')->insert(['admin_id'=>$res_admin['id'],'key'=>$key,'time'=>date('Y-m-d H:i:s'),'status'=>1]);
            if(!$res_login)
                return json(['data' => [], 'code' => 205, 'msg' => '登录授权失败']);

            db('admin')->where(['id'=>$res_admin['id']])->update(['last_login_time'=>date('Y-m-d H:i:s'),'last_login_ip'=>$this->request->ip()]);
            return json(['data' => ['id' => $res_admin['id'], 'username' => $data['username'],'key'=>$key], 'code' => 200, 'msg' => '登录成功']);
        }else{
            return json(['data'=>[],'code'=>301,'msg'=>'数据请求格式不正确']);
        }
    }

    //模拟运行接口，校验是否正确
    public function test(){
        $http = new \http\Http();
        $data = [
//            'file' => 'img_url',
//            'banner_name' => '广告标题修改',
            'page'  => '1',
            'limit'  => '10',
        ];
        $res = $http->post('http://www.aikeqin.com/admin/banner/listBanner',$data);
        dump(json_decode($res,true));
        dump($res);

    }




}

