<?php
/**
 * 后台公共类
 * User: 江振浩
 * Date: 2017年8月30日
 * Time: 14:07
 */
namespace app\common\controller;

use think\Controller;
use auth\Auth;


class AdminBase extends Controller {
    public static $admin_id;
    public static $res_key;
    public static $res_auth;
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$res_key = $this->getKey();
        self::$res_auth = $this->checkAuth();
    }


    /**
     * 根据key获取管理员id
     * 1.判断是否存在
     * 2.判断时间是否在2小时内
     * @param string key
     * @return json|int
     */
    public function getKey(){
        $key = '21505873691';//input('key',null);
        if(is_null($key))
            return json(['data'=>[],'code'=>403,'msg'=>'key不能为空']);

        $res = db('admin_login')->field('id,time,admin_id')->where(['key'=>$key,'status'=>1])->find();
        if(!$res)
            return json(['data'=>[],'code'=>404,'msg'=>'异常账号']);
        if(time() - strtotime($res['time']) > 3600*2)
            return json(['data'=>[],'code'=>405,'msg'=>'登录信息已失效']);
        db('admin_login')->where(['key'=>$key])->update(['time'=>date('Y-m-d H:i:s')]);
        self::$admin_id = $res['admin_id'];
        return $res['id'];
    }

    /**
     * 权限检查
     * @return bool
     */
    protected function checkAuth() {
        $module     = $this->request->module();
        $controller = $this->request->controller();
        $action     = $this->request->action();

        // 排除权限
        $not_check = ['admin/Index/index', 'admin/AuthGroup/getjson', 'admin/System/clear'];

        if (!in_array($module . '/' . $controller . '/' . $action, $not_check)) {
            $auth     = new Auth();
            if (!$auth->check($module . '/' . $controller . '/' . $action, self::$admin_id)) {
//                return json(['data'=>[],'code'=>406,'msg'=>'没有权限']);
                return true;
            }
        }
        return true;
    }



}