<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017年8月30日
 * Time: 15:06
 */
namespace app\common\controller;

use think\Controller;

class ApiBase extends Controller{
    public static $experience;
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 计算可用资金
     */
    public function callMoney($user_id){
        //充值+提现
        $res_money = db('money_log')->where('user_id','eq',$user_id)->where('status','eq','1')->sum('money');
        //冻结资金
        $where['a.user_id']     = $user_id;
        $where['r.examine_type'] = ['<>','3'];
        $where1['a.user_id']     = $user_id;
        $where1['r.examine_type'] = '1';
        $task_money = db('capital_freeze')->alias('a')->join('reward_task r','a.task_id = r.id')->where($where)->sum('r.reward_money');
        $task_money1 = db('capital_freeze')->alias('a')->join('reward_task r','a.task_id = r.id')->where($where1)->sum('r.reward_money');
        //分配资金
        $temp1 =[
            'detailed_type'=>'1',
            'user_id'=>$user_id,
        ]; //分配
        $temp3=[
            'detailed_type'=>'3',
            'user_id'=>$user_id,
        ]; //退款
        $detailed_money1 = db('capital_detailed')->where($temp1)->sum('money');//分配资金
        $detailed_money3 = db('capital_detailed')->where($temp3)->sum('money');//退款资金

        $tatol_money = $res_money - $task_money +  $detailed_money1 + $detailed_money3;

        $data['vail_money'] = $tatol_money;
        $data['tatol_money'] = $tatol_money + $task_money1;
        return $data;
    }

    /**
     * 获取用户id
     * @param string $openid
     * @return json|int
     */
    public function getUserId(){
        $openid = input('openid');
        if(empty($openid))
            return json(['data'=>[],'code'=>401,'msg'=>'openid不能为空']);
        $res_user = db('user_info')->field('id,experience')->where(['openid'=>$openid,'status'=>1])->find();
        if(empty($res_user))
            return json(['data'=>[],'code'=>402,'msg'=>'当前用户状态异常']);
        self::$experience = $res_user['experience'];
        return $res_user['id'];
    }
}