<?php
/**
 * 前端首页
 * Created by PhpStorm.
 * User: 小宝
 * Date: 2017年9月11日
 * Time: 14:40
 */
namespace app\api\controller;

use think\Db;
use \app\common\controller\ApiBase;

class Index extends ApiBase{

    //初始化
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取banner接口
     * 1、查询数据库
     *  1.1 数据为空返回提示
     * @param $parent_id  父级id
     */
    public function getBanner(){
        $data = $this->request->only(['parent_id']);

        //验证空值
        $res_require = $this->validate($data,'Index.index_banner');
        if($res_require !== true)
            return json(['data' =>[],'code' => '201','msg' => $res_require]);

        Db::startTrans();
        //读取
        $temp['parent_id'] = $data['parent_id'];
        if($res = db('banner')->where($temp)->select());
            return json(['data' => $res,'code' => '200','msg' => '获取成功']);
        Db::rollback();
        return json(['data' => [],'code' => '201','msg' => '获取失败']);
    }

    /**
     * 获取热门商品接口
     * 1、查询数据库符合条件的数据
     *  1.1 为空返回提示
     * @param  $limit  获取条数
     */
    public function getHotProduct(){
        $data = $this->request->only(['limit']);
        //条件
        $temp = [
            'hot' => '2',
            'status' => '1'
        ];
        //读取
        if($res = db('product')->where($temp)->limit($data['limit'])->select());
        return json(['data' => $res,'code' => '200','msg' => '获取成功']);
        Db::rollback();
        return json(['data' => [],'code' => '201','msg' => '获取失败']);
    }


}