<?php
/**
 * 用户等级类
 * Created by PhpStorm.
 * User: 小宝
 * Date: 2017年9月11日
 * Time: 14:40
 */
namespace app\admin\controller;

use think\Db;
use \app\common\controller\AdminBase;

class Level extends AdminBase{

    //初始化
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 添加用户等级接口
     * 1、验证数据格式是否正确
     *  1.1 数据格式错误 返回提示
     * 2、获取管理员信息
     *  2.1 管理员信息不存在 返回提示
     * 3、检查用户权限
     *  3.1 没有权限直接返回提示
     * 4、入库
     * @param $name   规格名称
     * @param $range_min  最小范围
     * @param $range_max  最大范围
     */
    public function addLevel(){
        $data = $this->request->only(['name','range_min','range_max']);
        //验证空值
        $res_require = $this->validate($data,'Level.level_add');
        if($res_require !== true)
            return json(['data' =>[],'code' => '201','msg' => $res_require]);

        //校验当前账户是否有效
        if(!is_int(self::$res_key))
            return self::$res_key;

        //校验权限
        if(!is_bool(self::$res_auth))
            return self::$res_auth;


        Db::startTrans();
        //入库
        $data['create_time']   = date('Y-m-d H:i:s',time());
        $data['creator_id']   = self::$admin_id;

        if(!($res = db('user_level')->insert($data))) {
            Db::rollback();
            return json(['data' => [],'code' => '201','msg' => '添加失败']);
        }else{
            Db::commit();
            return json(['data' => [], 'code' => '200', 'msg' => '添加成功']);
        }
    }

    /**
     * 修改用户等级接口
     * 1、接收等级id
     *  1.1 为空返回提示
     * 2、验证数据管理员权限
     *  2.1 返回提示
     * 3、验证数据是否存在
     *  3.1 不存在返回提示
     * 4、修改数据
     */
    public function updateLevel(){
        $data = $this->request->only(['name','range_min','range_max', 'sort','id']);

        //验证空值
        $this_val = [
            'name'      => $data['name'],
            'id'         => $data['id'],
            'range_min'         => $data['range_min'],
            'range_max'         => $data['range_max'],
        ];
        $res_require = $this->validate($this_val,'Level.level_update');
        if($res_require !== true)
            return json(['data' =>[],'code' => '201','msg' => $res_require]);

        //校验当前账户是否有效
        if(!is_int(self::$res_key))
            return self::$res_key;

        //校验权限
        if(!is_bool(self::$res_auth))
            return self::$res_auth;

        //验证目标数据是否存在
        $res_v = db('user_level')->field('id')->where('id',$data['id'])->find();
        if(!$res_v)
            return json(['data' =>[],'code' => '202','msg' => '数据不存在']);

        //处理排序
        if(isset($data['sort'])) {
            $sort = $data['sort'];
        }else{
            $sort = '1';
        }

        //更新
        $temp['id']  = $data['id'];
        $value = [
            'name'    => $data['name'],
            'range_min'    => $data['range_min'],
            'range_max'    => $data['range_max'],
            'sort'         => $sort,
            'change_id'        => self::$admin_id
        ];

        Db::startTrans();
        $res = db('user_level')->where($temp)->update($value);
        if(!$res){
            Db::rollback();
            return json(['data' => [],'code' => '201','msg' => '修改失败']);
        }else{
            Db::commit();
            return json(['data' => [],'code' => '200','msg' => '修改成功']);
        }
    }

    /**
     * 删除用户等级
     * 根据接收到的id  进行数据库数据的删除处理
     * 1、验证空值
     *  1.1 为空返回提示
     * 2、验证数据是否存在
     *  2.1 不存在返回提示
     * 3、执行删除
     */
    public function delLevel(){
        $data = $this->request->only(['id']);

        //验证空值
        $result = $this->validate($data,'Level.level_del');
        if($result!==true)
            return json(['data' => [],'code' => '201','msg' => $result]);

        //校验当前账户是否有效
        if(!is_int(self::$res_key))
            return self::$res_key;

        //校验权限
        if(!is_bool(self::$res_auth))
            return self::$res_auth;

        //遍历数组
        $id_array = explode(',',$data['id']);
        if(is_array($id_array)){
            foreach($id_array as $k=>$v){
                //删除
                $this_data = db('user_level')->delete($v);
            }
        }
        if($this_data!=0)
            return json(['data' => [],'code' => '200','msg' => '删除成功']);
        return json(['data' => [],'code' => '202','msg' => '删除失败']);
    }

    /**
     * 用户等级列表
     * 根据分页的页数与条数获取数据库相应的数据返回
     */
    public function listLevel(){
        $data = $this->request->only(['page','limit']);

        //验证空值
        $result = $this->validate($data,'Level.level_list');
        if($result!==true)
            return json(['data' => [],'code' => '201','msg' => $result]);

        //校验当前账户是否有效
        if(!is_int(self::$res_key))
            return self::$res_key;

        //校验权限
        if(!is_bool(self::$res_auth))
            return self::$res_auth;

        //获取数据
        $temp['status']  = '1';
        $cate_data = db('user_level')->where($temp)->order('id desc')->page($data['page'],$data['limit'])->select();
        if(empty($cate_data))
            return json(['data' => [],'code' => '201','msg' => '数据为空']);

        return json(['data' => $cate_data,'code' => '201','msg' => '获取成功']);
    }

}